"""Banned-terms regex filter.

Loads ``config/banned_terms.yaml`` and scans ALL turns (user AND
assistant) of every example for any hit. Fails on the first match.
This is the PRIMARY mechanical guard against Western names, places,
brands, and the politics/religion/alcohol-dating/partisan-history
content boundaries.

Categories whose values are nested dicts (e.g., ``american_places``
with ``states`` / ``cities`` / ``landmarks`` / ``regions``) are
flattened down to their top-level category name for matching and
reporting.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import yaml

from qwen_tutor.generation.filters.base import Filter, FilterableExample, FilterResult

DEFAULT_BANNED_TERMS_PATH = Path("config/banned_terms.yaml")


def _flatten(value: Any) -> list[str]:
    """Recursively collect string terms from a list/dict structure."""
    out: list[str] = []
    if isinstance(value, list):
        for item in value:
            if isinstance(item, str):
                out.append(item)
            else:
                out.extend(_flatten(item))
    elif isinstance(value, dict):
        for sub in value.values():
            out.extend(_flatten(sub))
    return out


def _load_categories(path: Path) -> dict[str, list[str]]:
    with path.open("r", encoding="utf-8") as fh:
        doc = yaml.safe_load(fh) or {}
    categories: dict[str, list[str]] = {}
    for cat, value in doc.items():
        if cat.startswith("_"):  # skip metadata
            continue
        terms = [t.strip() for t in _flatten(value) if isinstance(t, str) and t.strip()]
        # de-dupe while preserving order
        seen: set[str] = set()
        uniq: list[str] = []
        for t in terms:
            lk = t.lower()
            if lk in seen:
                continue
            seen.add(lk)
            uniq.append(t)
        if uniq:
            categories[cat] = uniq
    return categories


def _compile_pattern(terms: list[str]) -> re.Pattern[str]:
    """Case-sensitive alternation regex with word-boundary anchors.

    Proper nouns ("Sarah", "New York", "McDonald's") leaked by the
    teacher model are always capitalized in fluent output, so matching
    case-sensitively is what we want — otherwise "nice" the adjective
    incorrectly matches "Nice" the French city. The trade-off: a
    sentence-initial common word that happens to share spelling with
    a banned proper noun (e.g. "Reading is fun") could false-positive,
    but the banned-terms YAML is curated to avoid such collisions.
    """
    sorted_terms = sorted(terms, key=len, reverse=True)
    alternation = "|".join(re.escape(t) for t in sorted_terms)
    return re.compile(rf"(?<![A-Za-z])(?:{alternation})(?![A-Za-z])")


class BannedTermsFilter(Filter):
    name = "banned_terms"

    def __init__(
        self,
        banned_terms_path: str | Path = DEFAULT_BANNED_TERMS_PATH,
    ) -> None:
        self.categories = _load_categories(Path(banned_terms_path))
        self.patterns: dict[str, re.Pattern[str]] = {
            cat: _compile_pattern(terms) for cat, terms in self.categories.items()
        }

    # ----- helpers --------------------------------------------------------

    def _all_text(self, example: FilterableExample) -> list[tuple[str, str]]:
        """Return a list of ``(label, text)`` chunks to scan.

        For ``scenario_type == "redirect"`` dialogues we deliberately skip
        the learner's (user) turns — the redirect prompt's whole point is
        that the user *does* drop in a banned trigger (politics, alcohol,
        a Western default, etc.) and the assistant gracefully pivots. The
        assistant turns are still scanned: the tutor must never produce
        the banned content itself.
        """
        meta = getattr(example, "metadata", None)
        scenario_type = getattr(meta, "scenario_type", None)
        skip_user_turns = scenario_type == "redirect"

        chunks: list[tuple[str, str]] = []
        sp = getattr(example, "system_prompt", None)
        if sp:
            # System prompt is generated by us, not by the teacher, so
            # we can skip it — but leave room to enable later.
            pass
        msgs = getattr(example, "messages", None)
        if msgs is not None:
            for i, m in enumerate(msgs):
                if skip_user_turns and m.role == "user":
                    continue
                chunks.append((f"messages[{i}].{m.role}", m.content))
        for attr in ("chosen", "rejected"):
            v = getattr(example, attr, None)
            if v is not None and hasattr(v, "content"):
                chunks.append((attr, v.content))
        pm = getattr(example, "prompt_messages", None)
        if pm:
            for i, m in enumerate(pm):
                if skip_user_turns and m.role == "user":
                    continue
                chunks.append((f"prompt_messages[{i}].{m.role}", m.content))
        return chunks

    # ----- check ----------------------------------------------------------

    async def check(self, example: FilterableExample) -> FilterResult:
        hits: list[dict[str, Any]] = []
        for label, text in self._all_text(example):
            if not text:
                continue
            for category, pattern in self.patterns.items():
                for m in pattern.finditer(text):
                    hits.append(
                        {
                            "category": category,
                            "term": m.group(0),
                            "where": label,
                        }
                    )
                    if len(hits) >= 8:
                        # cap diagnostic noise; we already know it fails
                        break
                if len(hits) >= 8:
                    break
            if len(hits) >= 8:
                break

        if not hits:
            return FilterResult(passed=True, score=0.0)

        first = hits[0]
        reason = (
            f"banned-term hit ({first['category']}): "
            f"{first['term']!r} in {first['where']}"
        )
        return FilterResult(
            passed=False,
            score=float(len(hits)),
            reason=reason,
            metadata={"hits": hits},
        )
