"""build_pedagogy_extra_probe.py — build EVAL-ONLY extra pedagogy probes.

Reads the eval-only dialogues in eval_sets/pedagogy_extra_raw/ (generated by
gen_pedagogy_eval_extra.py, NOT training data), extracts pedagogy-redirect
probe records using the SAME violation-detection + metadata-validation logic
as build_eval_sets.build_redirect_probe, and writes
eval_sets/pedagogy_extra_probe.jsonl.

NON-OVERLAP GUARANTEE: excludes any seed_id already present in the existing
eval_sets/redirect_probe.jsonl pedagogy probes, so the extra probes are
disjoint from the current 21. Combined with those 21, this yields the
expanded ~60-probe pedagogy set for the §5.4 withholding eval.

These records are eval-only probes for the frozen A1/A3/B1-B4. They are
never used for training.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

import re

from build_eval_sets import (
    extract_seed_id,
    extract_variant_tag,
    load_jsonl,
)

LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2"]
RAW_DIR = ROOT / "eval_sets" / "pedagogy_extra_raw"
EXISTING_PROBE = ROOT / "eval_sets" / "redirect_probe.jsonl"
OUT = ROOT / "eval_sets" / "pedagogy_extra_probe.jsonl"
AXIS = "pedagogy"
STREAM = "pedagogy_redirect"

# Cap new probes per level. ~7/level x 6 = 42 new; +21 existing = 63 total.
# NOTE: a 63->100 expansion (CAP=14) was trialed and ABANDONED — withholding at
# temp 0.7 is a single-draw sampled behavior (greedy ~0.025), so the rate is
# high-variance run-to-run and the n=100 redraw gave A1 0.43 (vs the n=63 0.61,
# a high draw). The paper keeps the n=63 result; do NOT raise this cap.
CAP_PER_LEVEL = 7

# HIGH-PRECISION pedagogy-violation detector. These dialogues are
# pedagogy-by-construction (pedagogy_trigger present), but the grammar/vocab/
# translation request sits at a VARIABLE turn (6, 8, 12, ...) amid small talk,
# and the dialogue continues past it with the learner accepting the scaffold.
# The teacher did NOT emit violation_turn_idx for these eval-only dialogues,
# so we locate the violation turn by scanning USER turns for the grammar-ask
# signature and taking the LAST match (the ask comes after rapport-building;
# trailing turns are acceptances, not asks). Precision matters more than
# recall here — a missed dialogue is just skipped; a mis-located one would
# truncate at the wrong turn and corrupt the metric (the bug that produced
# the spurious 0.190 in the first attempt). We therefore require an explicit
# grammar-ask pattern, not merely "a user turn with a question mark".
_PED_ASK_RE = re.compile(
    r"how do (?:you|i|we) (?:say|conjugate|spell|use|translate|pronounce|write)\b"
    r"|what(?:'s| is) the (?:rule|word|answer|grammar|conjugation|meaning|"
    r"translation|past tense|present tense|plural|opposite|difference)\b"
    r"|what does .{0,25}? mean\b"
    r"|\bdo (?:i|we) (?:say|use|write) ['\"]?\w+['\"]? or ['\"]?\w+"
    r"|(?:tell|give|teach|show) me (?:the |a )?(?:rule|word|answer|"
    r"translation|grammar|conjugation|meaning|list)\b"
    r"|what(?:'s| is) (?:the )?(?:past|present|future) (?:tense|form)\b"
    r"|the (?:rule|grammar|conjugation|past tense|plural) (?:for|of)\b",
    re.IGNORECASE,
)


def _locate_pedagogy_violation(msgs: list[dict]) -> int | None:
    """Return the index of the LAST user turn matching the grammar-ask
    signature, or None if no user turn matches."""
    hits = [
        i for i, m in enumerate(msgs)
        if m.get("role") == "user" and _PED_ASK_RE.search(m.get("content", "") or "")
    ]
    return hits[-1] if hits else None


def _existing_pedagogy_seed_ids() -> set[str]:
    seeds: set[str] = set()
    if not EXISTING_PROBE.exists():
        return seeds
    for line in EXISTING_PROBE.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        r = json.loads(line)
        if (r.get("expected", {}) or {}).get("stream") == STREAM:
            sid = (r.get("source", {}) or {}).get("seed_id")
            if sid:
                seeds.add(sid)
    return seeds


def main() -> int:
    exclude = _existing_pedagogy_seed_ids()
    print(f"Excluding {len(exclude)} seed_ids already in the existing 21 pedagogy probes")

    out_records: list[dict] = []
    per_level: dict[str, int] = {}
    for level in LEVELS:
        p = RAW_DIR / f"{STREAM}_{level}.jsonl"
        if not p.exists():
            per_level[level] = 0
            continue
        dialogues = load_jsonl(p)
        cell: list[dict] = []
        for d in dialogues:
            sid = extract_seed_id(d["id"])
            if not sid:
                continue
            if sid in exclude:
                continue  # non-overlap with existing probes
            msgs = d.get("messages", [])
            meta = d.get("metadata", {}) or {}
            gen_meta = (meta.get("generation") or {}) if isinstance(meta, dict) else {}
            # Construction guarantee: must be a pedagogy_redirect dialogue.
            if not gen_meta.get("pedagogy_trigger"):
                continue
            # Locate the grammar-ask turn directly (high-precision scan).
            user_idx = _locate_pedagogy_violation(msgs)
            if user_idx is None or user_idx < 1:
                continue
            reason = "scan_pedagogy_ask"
            context = msgs[: user_idx + 1]
            v = extract_variant_tag(d["id"])
            src_meta = d.get("metadata", {}) or {}
            ur = src_meta.get("user_role") or {}
            mr = src_meta.get("model_role") or {}
            rec = {
                "id": f"pedagogy_extra_probe_{STREAM}_{sid}_{v}_{level}",
                "test_set": "redirect_probe",  # same schema as redirect_probe
                "cefr_level": level,
                "locale": src_meta.get("locale", "china"),
                "system_prompt": d.get("system_prompt", ""),
                "context_messages": context,
                "expected": {
                    "axis": AXIS,
                    "stream": STREAM,
                    "detection_reason": reason,
                    "violation_turn_idx": user_idx,
                    "violation_turn_content": context[user_idx]["content"],
                    "scenario_context": {
                        "topic": src_meta.get("topic", ""),
                        "subtopics": list(src_meta.get("subtopics", []) or []),
                        "user_role_name": ur.get("name", ""),
                        "user_role_description": ur.get("description", ""),
                        "model_role_name": mr.get("name", ""),
                        "model_role_description": mr.get("description", ""),
                        "locale": src_meta.get("locale", ""),
                        "cefr_level": src_meta.get("cefr_level", level),
                    },
                },
                "source": {
                    "seed_id": sid,
                    "source_dialogue_id": d["id"],
                    "stream": STREAM,
                    "eval_only": True,
                },
            }
            cell.append(rec)
        # deterministic cap per level (sort by id for reproducibility)
        cell.sort(key=lambda r: r["id"])
        cell = cell[:CAP_PER_LEVEL]
        out_records.extend(cell)
        per_level[level] = len(cell)

    out_records.sort(key=lambda r: r["id"])
    OUT.write_text(
        "\n".join(json.dumps(r, ensure_ascii=False) for r in out_records) + "\n",
        encoding="utf-8",
    )
    print(f"\nExtra pedagogy probes by level: {per_level}")
    print(f"Total NEW pedagogy probes: {len(out_records)}")
    print(f"Combined with existing 21 -> ~{len(out_records) + 21} pedagogy probes")
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
