"""make_multiseed_configs.py — derive multi-seed SFT configs for A1 and A3.

Tier-1 reproducibility reseed (§4.10/§6.1): retrain the two load-bearing
trained conditions (A1, A3) at 2 extra seeds each, on a SEPARATE output path
(no overwrite), checkpointing every 100 steps. Only seed/shuffle_seed/
output_dir/save_* are changed; data, recipe, epochs are identical to the
headline runs so the variance reported is pure training-seed variance.

Generates:
  config/paper_v2/training_a1_s123.yaml -> outputs/paper_v2/a1_s123/sft
  config/paper_v2/training_a1_s7.yaml   -> outputs/paper_v2/a1_s7/sft
  config/paper_v2/training_a3_s123.yaml -> outputs/paper_v2/a3_s123/sft
  config/paper_v2/training_a3_s7.yaml   -> outputs/paper_v2/a3_s7/sft
"""

from __future__ import annotations

import copy
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parent.parent
CFG = ROOT / "config" / "paper_v2"

# (base config, condition tag, base output stem)
BASES = [
    ("training_a1_full.yaml", "a1"),
    ("training_a3_no_specialized.yaml", "a3"),
]
SEEDS = [123, 7]


def main() -> None:
    written = []
    for base_name, tag in BASES:
        base = yaml.safe_load((CFG / base_name).read_text(encoding="utf-8"))
        for seed in SEEDS:
            cfg = copy.deepcopy(base)
            sft = cfg["sft"]
            sft["seed"] = seed
            sft["output_dir"] = f"outputs/paper_v2/{tag}_s{seed}/sft"
            # checkpoint every 100 steps (matches the a1_1ep convention)
            sft["save_strategy"] = "steps"
            sft["save_steps"] = 100
            sft["save_total_limit"] = 3
            sft.setdefault("data", {})["shuffle_seed"] = seed
            # Drop DPO / downstream sections we don't run for the reseed so the
            # config can't accidentally trigger DPO or overwrite headline paths.
            for k in ("dpo", "on_policy", "evaluation", "comparison", "gguf_export"):
                cfg.pop(k, None)
            # logging run-name for traceability
            cfg.setdefault("logging", {})["wandb_run_name_prefix"] = f"paper-v2-{tag}-seed{seed}"
            out = CFG / f"training_{tag}_s{seed}.yaml"
            out.write_text(
                "# AUTO-GENERATED by make_multiseed_configs.py — multi-seed reseed.\n"
                "# Identical to the headline " + tag + " config except seed/shuffle_seed/\n"
                "# output_dir/save_steps. SFT-only; separate path (no overwrite).\n"
                + yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True),
                encoding="utf-8",
            )
            written.append((out.name, sft["output_dir"], seed))

    print("Wrote multi-seed configs:")
    for name, outdir, seed in written:
        print(f"  {name:<28} seed={seed:<4} -> {outdir}")


if __name__ == "__main__":
    main()
