"""run_training.py  -  Single entrypoint for training and evaluation.

This script reads only ``config/training.yaml`` and runs the following 7 stages
in order. The required raw data must already be generated by
``scripts/run_generation.py``.

    train_sft           SFT LoRA training
    eval_intermediate   holdout evaluation right after SFT (score baseline)
    on_policy_gen       regenerate one turn with the SFT adapter and collect additional DPO pairs
    filter_dpo          filter both dpo_raw/register and dpo_raw/on_policy
    train_dpo           additional DPO training on top of SFT
    eval_final          holdout evaluation right after DPO
    compare             compare intermediate vs final metrics

Training uses a lot of GPU memory. It is not expected to run on RTX 3060 (12GB)
and assumes RTX 5090 (32GB) or larger.

Usage:
    # Run all stages
    python scripts/run_training.py

    # Only SFT (skip DPO and on-policy)
    python scripts/run_training.py --stages train_sft,eval_intermediate

    # Only evaluation stages
    python scripts/run_training.py --stages eval_intermediate,eval_final,compare
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import os
import sys
import time
from pathlib import Path
from typing import Any

import yaml

# Windows consoles (cp1252/cp949) cannot print Singapore by default,
# which can cause UnicodeEncodeError in argparse --help text. Reconfigure
# stdout/stderr as UTF-8 so help and print output are not corrupted.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8")

# ---------------------------------------------------------------------------
# Add src/ to sys.path (for cases where the package is not installed editable)
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

os.environ.setdefault("QWEN_TUTOR_PROMPTS", "compact")
# Offline-by-default: prevent any silent network call to the Hugging Face Hub
# during training, eval, or trl init. Required for air-gapped operation. Users
# can override by setting these vars explicitly before launching the script.
os.environ.setdefault("HF_HUB_OFFLINE", "1")
os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")

logger = logging.getLogger("run_training")

ALL_STAGES = (
    "train_sft",
    "eval_intermediate",
    "on_policy_gen",
    "filter_dpo",
    "train_dpo",
    "eval_final",
    "compare",
)


# ---------------------------------------------------------------------------
# Config loading
# ---------------------------------------------------------------------------


def _load_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def _generation_levels(gen_cfg_path: Path) -> list[str]:
    """Load the CEFR level list used by filtering/evaluation from generation.yaml."""
    gen_cfg = _load_yaml(gen_cfg_path)
    return gen_cfg.get("generation", {}).get("cefr_levels", ["A1", "A2", "B1", "B2", "C1", "C2"])


# ---------------------------------------------------------------------------
# 1) SFT training
# ---------------------------------------------------------------------------


def _stage_train_sft(train_cfg_path: Path) -> None:
    """Run SFT training. The output directory is training.yaml's sft.output_dir."""
    print("\n=== train_sft ===")
    from qwen_tutor.training.sft import run_sft

    out_dir = run_sft(str(train_cfg_path))
    print(f"  SFT adapter saved to: {out_dir}")


# ---------------------------------------------------------------------------
# 2) On-policy DPO pair generation (regenerate one turn with the trained SFT model)
# ---------------------------------------------------------------------------


async def _stage_on_policy_gen(
    train_cfg: dict[str, Any], train_cfg_path: Path, gen_cfg_path: Path
) -> None:
    """Generate one policy output turn with the trained SFT adapter, compare it
    with the teacher, choose the more natural option as chosen, and add it to
    ``data/dpo_raw/on_policy_<level>.jsonl``.
    """
    op_cfg = train_cfg.get("on_policy", {})
    if not op_cfg.get("enabled", True):
        print("\n=== on_policy_gen (skipped, on_policy.enabled=false) ===")
        return
    print("\n=== on_policy_gen ===")

    from qwen_tutor.generation.on_policy_pairs import generate_batch
    from qwen_tutor.generation.teacher import build_teacher_from_config
    from qwen_tutor.training.eval.run_eval import HFTargetModelClient

    levels = _generation_levels(gen_cfg_path)
    target = HFTargetModelClient.from_pretrained(
        base_model_id=train_cfg["base_model"]["model_id"],
        adapter_path=op_cfg.get("adapter_path", "outputs/sft"),
    )
    judge = build_teacher_from_config(str(gen_cfg_path), role="judge")
    result = await generate_batch(
        target=target,
        cefr_levels=levels,
        sft_filtered_dir="data/sft_filtered",
        output_dir="data/dpo_raw",
        config_path=str(gen_cfg_path),
        judge=judge,
        min_margin=op_cfg.get("min_margin", 2),
        max_per_level=op_cfg.get("max_per_level"),
        concurrency=op_cfg.get("concurrency", 4),
        target_max_tokens=op_cfg.get("target_max_tokens", 320),
        target_temperature=op_cfg.get("target_temperature", 0.7),
    )
    print(f"  on-policy pairs written: {result}")


# ---------------------------------------------------------------------------
# 3) DPO filtering (both register and on_policy)
# ---------------------------------------------------------------------------


async def _stage_filter_dpo(gen_cfg_path: Path) -> None:
    """Filter both raw DPO inputs: register_*.jsonl and on_policy_*.jsonl.

    The filter configuration uses the filtering block from ``config/generation.yaml``.
    """
    print("\n=== filter_dpo (register + on_policy) ===")
    from qwen_tutor.generation.filters.banned_terms import BannedTermsFilter
    from qwen_tutor.generation.filters.mode_consistency import ModeConsistencyFilter
    from qwen_tutor.generation.filters.naturalness import NaturalnessFilter
    from qwen_tutor.generation.filters.pipeline import FilterPipeline
    from qwen_tutor.schemas import DPOExample

    gen_cfg = _load_yaml(gen_cfg_path)
    fcfg = gen_cfg.get("filtering", {})
    filters_list: list = [
        BannedTermsFilter(),
        ModeConsistencyFilter(),
        NaturalnessFilter(),
    ]
    if fcfg.get("enable_locale_judge"):
        from qwen_tutor.generation.filters.locale_judge import LocaleLLMJudge
        from qwen_tutor.generation.teacher import build_teacher_from_config

        judge = build_teacher_from_config(str(gen_cfg_path), role="judge")
        filters_list.append(LocaleLLMJudge(judge=judge))

    pipeline = FilterPipeline(
        filters_list, short_circuit=fcfg.get("short_circuit", True)
    )
    in_dir = Path("data/dpo_raw")
    out_dir = Path("data/dpo_filtered")
    out_dir.mkdir(parents=True, exist_ok=True)
    levels = _generation_levels(gen_cfg_path)
    for level in levels:
        for prefix in ("register", "on_policy"):
            in_path = in_dir / f"{prefix}_{level}.jsonl"
            if not in_path.exists():
                continue
            examples = list(DPOExample.from_jsonl(in_path))
            base = f"{prefix}_{level}"
            passed_path = out_dir / f"{base}_passed.jsonl"
            failed_path = out_dir / f"{base}_failed.jsonl"
            for p in (passed_path, failed_path):
                if p.exists():
                    p.unlink()
            summary = await pipeline.run_stream(
                examples,
                passed_path=passed_path,
                failed_path=failed_path,
                concurrency=fcfg.get("concurrency", 2),
                progress_desc=f"filter_dpo[{base}]",
            )
            print(f"  {base}: {summary}")


# ---------------------------------------------------------------------------
# 4) DPO training
# ---------------------------------------------------------------------------


def _stage_train_dpo(train_cfg_path: Path) -> None:
    print("\n=== train_dpo ===")
    from qwen_tutor.training.dpo import run_dpo

    out_dir = run_dpo(str(train_cfg_path))
    print(f"  DPO adapter saved to: {out_dir}")


# ---------------------------------------------------------------------------
# 5) Holdout evaluation (intermediate / final)
# ---------------------------------------------------------------------------


async def _stage_eval(
    *,
    train_cfg: dict[str, Any],
    train_cfg_path: Path,
    gen_cfg_path: Path,
    which: str,  # "intermediate" | "final"
    run_id: str,
) -> str:
    print(f"\n=== eval_{which} ===")
    from qwen_tutor.training.eval.run_eval import build_runner

    ecfg = train_cfg.get("evaluation", {})
    adapter = (
        ecfg.get("intermediate_adapter_path", "outputs/sft")
        if which == "intermediate"
        else ecfg.get("final_adapter_path", "outputs/dpo")
    )
    runner = build_runner(
        training_yaml=str(train_cfg_path),
        generation_yaml=str(gen_cfg_path),
        adapter_path=adapter,
    )
    out_root = Path("data/eval_results")
    full_run_id = f"{run_id}_{which}"
    summary = await runner.run_holdout(
        holdout_dir=ecfg.get("holdout_dir", "data/holdout"),
        output_dir=out_root,
        cefr_levels=_generation_levels(gen_cfg_path),
        n_per_level=ecfg.get("n_per_level", 5),
        run_id=full_run_id,
        concurrency=ecfg.get("concurrency", 4),
    )
    print(f"  run_id: {summary['run_id']}, n_examples: {summary['n_examples']}")
    return full_run_id


# ---------------------------------------------------------------------------
# 6) intermediate vs final comparison
# ---------------------------------------------------------------------------


def _stage_compare(train_cfg: dict[str, Any], run_id: str) -> int:
    """Compare eval_intermediate and eval_final results for regression."""
    print("\n=== compare ===")
    from qwen_tutor.training.eval.compare import compare_runs

    base_dir = Path("data/eval_results") / f"{run_id}_intermediate"
    cand_dir = Path("data/eval_results") / f"{run_id}_final"
    if not base_dir.exists() or not cand_dir.exists():
        print(f"  Required directories for comparison are missing: {base_dir} / {cand_dir}")
        return 0
    ccfg = train_cfg.get("comparison", {})
    report = compare_runs(
        baseline_run=base_dir,
        candidate_run=cand_dir,
        threshold=ccfg.get("threshold", 0.05),
    )
    out_md = cand_dir / "compare_report.md"
    out_md.write_text(report.format_text(), encoding="utf-8")
    print(f"  comparison report: {out_md}")
    if ccfg.get("fail_on_regression") and bool(report.regressions):
        print("  Regression detected, returning exit code 1.")
        return 1
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="qwen-en-tutor training and evaluation pipeline",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--training-config", default="config/training.yaml")
    p.add_argument("--generation-config", default="config/generation.yaml")
    p.add_argument(
        "--stages",
        default=",".join(ALL_STAGES),
        help="Stages to run (comma-separated). Default: all.",
    )
    p.add_argument(
        "--run-id",
        default=None,
        help="Prefix for evaluation result directory names. Default: current timestamp.",
    )
    p.add_argument("-v", "--verbose", action="store_true")
    return p.parse_args()


def _validate_stages(stages: list[str]) -> list[str]:
    bad = [s for s in stages if s not in ALL_STAGES]
    if bad:
        raise SystemExit(f"Invalid stage(s): {bad!r}. Valid values: {list(ALL_STAGES)}")
    return stages


async def _main() -> int:
    args = _parse_args()
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )
    train_cfg_path = Path(args.training_config)
    gen_cfg_path = Path(args.generation_config)
    for p in (train_cfg_path, gen_cfg_path):
        if not p.exists():
            raise SystemExit(f"Config file not found: {p}")
    train_cfg = _load_yaml(train_cfg_path)
    stages = _validate_stages([s.strip() for s in args.stages.split(",") if s.strip()])
    run_id = args.run_id or time.strftime("%Y%m%dT%H%M%S")

    exit_code = 0
    for stage in stages:
        if stage == "train_sft":
            _stage_train_sft(train_cfg_path)
        elif stage == "eval_intermediate":
            await _stage_eval(
                train_cfg=train_cfg,
                train_cfg_path=train_cfg_path,
                gen_cfg_path=gen_cfg_path,
                which="intermediate",
                run_id=run_id,
            )
        elif stage == "on_policy_gen":
            await _stage_on_policy_gen(train_cfg, train_cfg_path, gen_cfg_path)
        elif stage == "filter_dpo":
            await _stage_filter_dpo(gen_cfg_path)
        elif stage == "train_dpo":
            _stage_train_dpo(train_cfg_path)
        elif stage == "eval_final":
            await _stage_eval(
                train_cfg=train_cfg,
                train_cfg_path=train_cfg_path,
                gen_cfg_path=gen_cfg_path,
                which="final",
                run_id=run_id,
            )
        elif stage == "compare":
            rc = _stage_compare(train_cfg, run_id)
            if rc != 0:
                exit_code = rc

    print("\n=== training pipeline complete ===")
    return exit_code


if __name__ == "__main__":
    sys.exit(asyncio.run(_main()))
